# mutation: Create Category

mutation createCategory {
    createCategory(input: { name: "Tecnologia", description: "Cursos de Tecnologia" }) {
        id
        name
        description
    }
}

# query: Get Categories

query queryCategory {
    categories {
        id
        name
        description
    }
}