mutation createCategory {
  createCategory(
    input: {name: "Category 1", description: "Category 1 description"}
  ) {
    id
    name
    description
  }
}

query queryCategories {
  categories {
    id
    name
    description
  }
}

mutation createCourse {
  createCourse(input: {name: "Full Cycle", description: "A hands-on course!", categoryId: "b44a7ce0-ccb6-4f76-9cd2-7e2268a91cc1"}) {
    id
    name
  }
}

query queryCourses {
  courses {
    id
    name
  }
}